# Emails
SENDGRID_USERNAME: 'app24867060@heroku.com'
SENDGRID_PASSWORD: 'uhwyqupx1340'
SENDGRID_TEMPLATE_RECEIPT: '8bce8dd6-cc97-41bf-b95d-745c9e241c95'
SENDGRID_TEMPLATE_REMINDER_24: '2a8e2d8c-b131-4cdc-9e5f-093e46ca1ad3'
SENDGRID_TEMPLATE_REMINDER_3: '569766a5-df72-41f4-aecb-db3e10b2d3b1'
SENDGRID_TEMPLATE_TEST: 'c5935654-51fe-4f08-aafe-a7a8b84f8e32'

# Purchasing
BRAINTREE_PUBLIC_KEY: 'y3p32zdr5znp8426'

####Switch to sandbox in own account for testing purposes
BRAINTREE_PRIVATE_KEY: '12a0a9c932911e9672f82cf9d04da42a'
BRAINTREE_MERCHANT_ID: 'vrxmdnzpqwjhv39q'
BRAINTREE_MERCHANT_MASTER_ID: 'mwkfzymmk7yhtc7n'
BRAINTREE_ENCRYPTION_KEY: '9 2&\xE3\x86\xA64\xBD\xDD\n<c\x80\x12\xFA_\x8Ee\x98*\xD8\x86\xB1#\xA4_\x7Fp\"\xE2\xA8'
####



# Amazon
# AWS_ACCESS_KEY_ID: 'AKIAIL4DMTK5MRD4AQOA'
# AWS_SECRET_ACCESS_KEY: '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'
S3_BUCKET_NAME: 'kmda-test-dl2'

# Social Media
INSTAGRAM_ACCESS_TOKEN: '489376088.9b9ab64.e718f7e23f5c4fdbbf6ed07c16b5a521'